### PR TITLE
First implementation

### PR DESCRIPTION
**Pull request by yconsj**
Dense function and forward propagation.

### CODE REVIEW

**Comment by yconsj** [comment]
note: i needed to change #include <cstdint> (cpp) in the provided models to #include <stdint.h> (c)

**Comment by AminHasanpour** [comment]
"nn_from_scratch/model/convert/c_templates" contains templates that the script will use and fill in to produce the C and header files required by your C code. So, you should not change them, and you should not include this path in "f_prop.h".
Instead, you can put the C and header files I gave you in email in the "nn_from_scratch/hardware/model" directory and include it in "f_prop.h" like: `#include "model/model.h"`

**Review by AminHasanpour — CHANGES_REQUESTED** [review]
@yconsj The problem mentioned in "Conversation" should be resolved.

**Comment by yconsj** [comment]
That is my mistake for misunderstanding, I have committed the requested changes, and reverted the templates I had changed.

**Pull request merged**
